name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
        
    - name: Set up Mockgen
      run: go install github.com/golang/mock/mockgen@v1.6.0
      
    - name: Generate
      run: go generate -v ./...

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
